### ISSUE TITLE
Get Tool to reverse engineer Agency Database

### ISSUE THREAD

**Issue by norabu2** [SeattleDataforGood/Marys_Place_Project#2]
Goal is to understand the data base schema as a basis for possible the visualizations.

**Comment by hburgmeier** [comment]
This tool should work:
http://mogwai.sourceforge.net/erdesignerng.html

Part of the task is to setup a PostgreSQL database. Install the Agency database (https://sourceforge.net/p/agency/code/ci/master/tree/) and then try to reverse engineer in the tool.

**Comment by norabu2** [comment]
Tom: Can we get a copy of the DB (only example data)?
Reach out to Ken: Can we reach out to Ken and ask him for the schema?
Can we get an export of the data structure?
Are the tables populated.

**Comment by hburgmeier** [comment]
I set up the AGENCY database on PostgreSQL and tried to reverse engineer it. The tool I suggested gets stuck very early on with a domain problem. I think I check out the tool support or search for a better tool.

**Comment by hburgmeier** [comment]
Just as a detail, I have a running PostgreSQL database with the initial (empty) schema. Let me know if you want to take a try at reverse engineering it.

**Comment by hburgmeier** [comment]
I used www.dbschema.com to reverse engineer the database (unfortunately a commerical tool). I uploaded a png export of the schema to the github.

**Comment by hburgmeier** [comment]
See the export here: https://github.com/SeattleDataforGood/Marys_Place_Project/tree/master/database
