### ISSUE TITLE
Research HMIS requirements

### ISSUE THREAD

**Issue by norabu2** [SeattleDataforGood/Marys_Place_Project#24]
Assigned to Matt.
Matt: I’ve found the 2004 requirements. I have not seen a reference to a later set of standards but am still looking through the HUD website. I haven’t had a chance to review this doc yet though. https://www.hudexchange.info /resources/documents/2004HUDDataandTechnicalStandards.pdf

**Comment by matthewloskamp** [comment]
#

**Comment by matthewloskamp** [comment]
I'll do some more research here before Tuesday

**Comment by matthewloskamp** [comment]
http://kingcounty.hmis.cc/wp-content/uploads/2015/09/Partner-Agency-User-Agreement.pdf \

See item K on page 7.

K. The Agency may use non¬identifying client information from HMIS regarding the services provided by the Agency for funding, auditing, or planning purposes. If the Agency wishes to provide information from HMIS beyond information related solely to services provided by the Agency, it must first inform and receive approval from the County as the HMIS lead.

**Comment by matthewloskamp** [comment]
Additional research would be appreciated, but based on this document we should be ok.
