### ISSUE TITLE
Follow up with Tableau

### ISSUE THREAD

**Issue by norabu2** [SeattleDataforGood/Marys_Place_Project#45]
- Find the contact within Tableau
- Clarify questions below - if OK:
- Find right people in Mary's Place
- Setup joint meeting

Questions:
- Would the free licenses include support for how to questions? 
- How could we handle security requirements and user management (access hierarchy)?
- Could we get a hosted Tableau Server (publish dashboards etc.)? Manageability of access is very important.
- How would you handle version upgrades?
- How long is Mary`s Place eligible for free licenses? How long is the license good for?
- Backwards compatibility? 
- What about forecasting calculation?
- Partner with SDFG or with Mary's Place directly?
Later:
- Upscale to other shelters?

**Comment by ShaunaSeattle** [comment]
Here is what I heard back from Ashley Monson at Tableau Foundation, her answers in **Bold.**

What we'd like to do is to get answers to a few high level questions, then hand that info off to Mary's Place and let someone there make the final decision and arrangements, if they decide to go for Tableau in-house.  Here is our list of questions:
 
1. What additional info  (if any) do you need from Mary's Place?   Financial info, etc?
**We go through TechSoup for nonprofit license distribution and organization vetting. Mary’s Place should request a license through TechSoup to determine whether they are eligible for the program. Here's the link: _http://www.techsoup.org/products/tableau-desktop-professional--2-year-subscription--G-49474--**_ 
 
2. Are there any support or training options for non-profits?  If they have questions about using the product, is there anyone at Tableau they can contact for assistance?
**Absolutely! The Tableau Service Corps offers one-on-one help specifically for nonprofits trying to get started with Tableau. In addition, the licenses available through TechSoup come with the full tech support available to all of our other customers – there is no difference between the Desktop product we sell and the one available through TechSoup. We also have a great library of free training videos on our website that are available to everyone.** 
 
3. Is there an option for non-profits for Tableau Online, or is their opportunity just licenses for Tableau Desktop? 
**Only Desktop is available through TechSoup right now. Tableau Public and Tableau Reader and both great free options for sharing visualizations.** 
 
4. How long is a license (Desktop or Online if applicable) good for?  Is there a renewal process, etc?  How many licenses do you typically grant per organization? 
**The Desktop Licenses are good for 2 years, but the organization can just request more licenses through TechSoup at the end of the 2 year period. The time limit is just intended as a check-in to make sure an organization still meets the requirements for our donated software program. Each organization can obtain up to 5 copies of Tableau Desktop through TechSoup. You don’t have to request all 5 at once either. You can start with one or two and increase as demand requires.**
 
**I think that covers the basics, but feel free to reach out if I can help with anything else**

**Comment by matthewloskamp** [comment]
Can Tableau reader connect with a live connection to DB

**Comment by nmannheimer** [comment]
Hey Matt,

Tableau reader is extract only, so the data would have to be packaged in a twbx as a tde == static data. The data thus can't be live.

Sincerely,
Nathan

**Comment by matthewloskamp** [comment]
Thanks Nathan!!
